在`Go`语言中，`panic`是一种运行时错误，表示程序发生了不可恢复的错误。会发生`panic`的代码可以通过编译，也没有有效的方法在代码中捕捉这个错误。当程序出现`panic`时，会立即停止当前函数的执行，并沿着调用栈向上返回，然后程序崩溃并打印调用栈信息。

### 一、会发生`panic`的情况

#### 1. 空指针的解引用（空指针异常）

```go
var ptr *int
*ptr = 10 // panic: runtime error: invalid memory address or nil pointer dereference
```

上面的代码中，声明了一个指针，但没有给它分配内存，它会被设置默认值`nil`，而`nil`是无法解引用的。

不会`panic`的写法有以下几种：

```go
var ptr *int
ptr = new(int) // 为指针分配内存
*ptr = 10

var num int
ptr := &num // 指针ptr指向num
*ptr = 20
fmt.Println(*ptr)
```

#### 2. 调用`nil`函数

```go
var f func()
f() // panic: runtime error: invalid memory address or nil pointer dereference
```

这种情况也属于空指针的解引用，即空指针异常问题。

#### 3. 手动调用`panic()`函数

```go
panic("A serious error has occurred")
```

#### 4. 切片越界访问

```go
slice := []int{1, 2, 3}
_ = slice[5] // panic: runtime error: index out of range [5] with length 3
```

对切片或字符串进行切片操作来获取子串时，也可能发生切片越界问题：

```go
str := "hello"
subStr := str[:6] // panic: runtime error: slice bounds out of range [:6] with length 5
```

在写代码时要时刻注意，切片不要越界，以规避这种报错。


#### 5. 类型断言失败

```go
var i interface{} = "hello"
res := i.(int) // panic: interface conversion: interface {} is string, not int
```

这种情况是因为我们省略了类型断言的第二个参数`ok`，我们需要加上它并进行判断，或者也可以忽略此参数：

```go
var i interface{} = "hello"
res, ok := i.(int)
if !ok {
	fmt.Println("interface {} is not int")
}

res, _ := i.(int)  // 这样也不会panic了，res得到的是int类型的零值，也就是0
```

#### 6. 关闭已关闭的通道

```go
ch := make(chan int)
close(ch)
close(ch) // panic: close of closed channel
```

#### 7. 关闭未初始化的通道

```go
var ch chan int
close(ch) // panic: close of nil channel
```

#### 8. 向已关闭的通道发送数据

```go
ch := make(chan int, 2)
ch <- 1
ch <- 2
close(ch)
ch <- 3  // panic: send on closed channel
```

#### 9. 向未初始化的通道进行读写操作

```go
var ch chan int
ch <- 42  // fatal error: all goroutines are asleep - deadlock!
x := <-ch // fatal error: all goroutines are asleep - deadlock!
```

类似这种死锁错误，实际上不属于`panic`，而属于`fatal`；关于`panic`和`fatal`的区别见最底内容。

#### 10. 除以`0`（分母为`0`）

```go
x := 10
y := 0
_ = x / y // panic: runtime error: integer divide by zero
```

#### 11. `sync.WaitGroup`计数器小于`0`

```go
var wg sync.WaitGroup
wg.Add(1)
go func() {
	defer wg.Done()
}()
go func() {
	defer wg.Done()
}()
wg.Wait()
```

这种情况可能出现`panic: sync: negative WaitGroup counter`错误，通常表明在使用`WaitGroup`时，其计数器的值变成了负数。这通常是因为`WaitGroup`的`Add`方法和`Done`方法的调用不匹配导致的。因此，确保`WaitGroup`的计数器值与实际`goroutine`的数量一致非常重要。在上面的代码中，由于启动了两个`goroutine`，因此`WaitGroup`的计数器值应该设置为`2`。

### 二、对`panic`的捕捉处理

在`Go`语言中，`panic`并不是无法处理的异常。实际上，`recover()`函数提供了一种方式来捕获并处理`panic`。`recover()`是`Go`内建函数，用于恢复执行，并返回`panic`时传递的值。需要注意的是，`recover()`只能在`defer`语句中生效。

`recover()`函数的函数签名如下所示：

```go
func recover() interface{}
```

一般来说，使用`recover()`的方式如下：

```go
defer func() {
	if r := recover(); r != nil {
		fmt.Println("catch panic: %v\n", r)
	}
    fmt.Println("hello world!")  // 这里的代码仍然会执行
}()
```

在此示例中，即便发生了`panic`，通过`recover()`捕获后，`defer`语句块中的后续代码仍然会执行。默认情况下，`panic`会打印堆栈信息，但如果被`recover()`捕获，则堆栈信息不会打印。

> **注意：** 需要特别指出的是，`recover()`不能捕获主程序中的`goroutine`发生的`panic`。如果你希望捕获某个`goroutine`中的`panic`，必须在该`goroutine`内部的`defer`语句中使用`recover()`。

### 三、`panic`和`fatal`的区别

`panic`和`fatal`都表示程序的终止，但它们的含义和触发方式有所不同：

`fatal`表示发生了一个致命错误，可以由`log.Fatal`函数引起，它会调用`os.Exit(1)`立即终止程序；另一种常见的`fatal`是死锁错误：`fatal error: all goroutines are asleep - deadlock!`。这种终止方式表示程序遇到了不可恢复的严重问题，无法继续执行，`fatal error`也无法被`recover()`函数捕捉，程序的终止是不可避免的，程序员需要立即修复问题。

`panic`表示发生了一个严重错误，而当前执行环境无法处理该错误，因此程序需要终止。但与`fatal`不同，`panic`通常是可恢复的，程序员可以通过`recover`函数捕获并处理`panic`，从而避免程序的完全终止。

简而言之，`fatal`表示程序终止是不可避免的，而`panic`表示程序终止是可避免的，只是当前执行环境无法处理该错误。
